# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml README.md uv.lock /app/
COPY src /app/src

# Install dependencies
RUN pip install --no-cache-dir .

# Expose no port for stdio server

# Set entrypoint
ENTRYPOINT ["blocknative-mcp"]
